### ISSUE TITLE
advancedgarage doesnt work with kashacters

### ISSUE THREAD

**Issue by LeCyreaxYT** [KASHZIN/kashacters#23]
i have the problem that 

My Cars on esx_advancedgarage not showing up.

i think esx_advancedgarage can not find the cars

![da99d08d83aa2d562f3c9a61b76db303](https://user-images.githubusercontent.com/38440842/58576654-1e0c7d00-8245-11e9-9dc3-81fa2c65da79.png)

the steam: has ben change to char1 to char4 can you send me a fix for esx_advancedgarage.

MfG.

**Comment by Blejki** [comment]
+1

**Comment by Ex0r** [comment]
Did you add the 'owner' column and the owned_vehicles table to the kashacters config file as an identifier table that needs updated?
